insert into cliente(nombres, apellidos) values('Juan Carlos', 'García López');
insert into cliente(nombres, apellidos) values('Ana María', 'Pérez Sánchez');
insert into cliente(nombres, apellidos) values('Carlos Eduardo', 'Martínez Rodríguez');
insert into cliente(nombres, apellidos) values('María José', 'Hernández González');
insert into cliente(nombres, apellidos) values('José Luis', 'Gómez Pérez');
insert into cliente(nombres, apellidos) values('Laura Beatriz', 'Díaz Fernández');
insert into cliente(nombres, apellidos) values('Pedro Antonio', 'Ruiz García');
insert into cliente(nombres, apellidos) values('Raquel Isabel', 'Sánchez Martín');
insert into cliente(nombres, apellidos) values('Javier Andrés', 'Moreno Jiménez');
insert into cliente(nombres, apellidos) values('Sandra Elena', 'Ramírez Díaz');
insert into cliente(nombres, apellidos) values('Francisco Javier', 'López Sánchez');
insert into cliente(nombres, apellidos) values('Lucía Patricia', 'Vázquez García');
insert into cliente(nombres, apellidos) values('Antonio Miguel', 'Martín Rodríguez');
insert into cliente(nombres, apellidos) values('Susana María', 'Torres Gómez');
insert into cliente(nombres, apellidos) values('Ricardo Alejandro', 'Fernández López');
insert into cliente(nombres, apellidos) values('Verónica Isabel', 'García Ruiz');
insert into cliente(nombres, apellidos) values('Eduardo Francisco', 'Martínez López');
insert into cliente(nombres, apellidos) values('Marta Elena', 'Pérez Gómez');
insert into cliente(nombres, apellidos) values('Víctor Manuel', 'Álvarez Ruiz');
insert into cliente(nombres, apellidos) values('Isabel Cristina', 'Serrano Romero');


insert into producto(nombre, precio) values('Pizza Margherita', 9.99);
insert into producto(nombre, precio) values('Hamburguesa Clásica', 5.49);
insert into producto(nombre, precio) values('Pechuga de Pollo a la Parrilla', 8.99);
insert into producto(nombre, precio) values('Tacos de Carne Asada', 7.50);
insert into producto(nombre, precio) values('Ensalada César con Pollo', 6.99);
insert into producto(nombre, precio) values('Spaghetti Bolognese', 11.00);
insert into producto(nombre, precio) values('Sushi de Atún', 12.99);
insert into producto(nombre, precio) values('Paella de Mariscos', 15.00);
insert into producto(nombre, precio) values('Tartar de Salmón', 14.50);
insert into producto(nombre, precio) values('Alitas de Pollo con Salsa BBQ', 6.49);
insert into producto(nombre, precio) values('Hamburguesa Vegana', 8.00);
insert into producto(nombre, precio) values('Croissant de Mantequilla', 2.50);
insert into producto(nombre, precio) values('Tarta de Frambuesa', 4.99);
insert into producto(nombre, precio) values('Muffins de Arándano', 3.50);
insert into producto(nombre, precio) values('Churros con Chocolate', 5.00);
insert into producto(nombre, precio) values('Pasta Carbonara', 10.50);
insert into producto(nombre, precio) values('Burritos de Pollo', 7.99);
insert into producto(nombre, precio) values('Falafel con Hummus', 6.99);
insert into producto(nombre, precio) values('Pasta Pesto', 9.50);
insert into producto(nombre, precio) values('Empanadas de Carne', 3.00);
insert into producto(nombre, precio) values('Ceviche de Pescado', 11.00);
insert into producto(nombre, precio) values('Tacos al Pastor', 6.00);
insert into producto(nombre, precio) values('Galletas de Chocolate', 2.99);
insert into producto(nombre, precio) values('Donas Glaseadas', 1.99);
insert into producto(nombre, precio) values('Ensalada Griega', 7.50);
insert into producto(nombre, precio) values('Wrap de Pollo y Aguacate', 7.00);
insert into producto(nombre, precio) values('Ramen de Cerdo', 9.99);
insert into producto(nombre, precio) values('Poke Bowl de Atún', 13.50);
insert into producto(nombre, precio) values('Sopa de Lentejas', 4.50);
insert into producto(nombre, precio) values('Sándwich de Jamón y Queso', 5.00);
insert into producto(nombre, precio) values('Tarta de Limón', 5.99);
insert into producto(nombre, precio) values('Kebabs de Cordero', 8.50);